[package]
name = "sockdig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netlink-packet-sock-diag = "0.4.0"
netlink-sys = "0.8.3"
